Training data: 360
Validation data: 240
input_samples (?, 32000)
input_samples_reshape (?, 32000, 1)
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
3D Conv Out: (?, 50, 32, 32, 64)
3D Conv Out Reshape: (?, 32, 32, 64)
Resnet18 Out: (?, 1, 1, 512)
Resnet18 Linear Out: (?, 256)
Input to GRU: (?, 50, 256)
GRU Out: (?, 50, 29)
ResNet LSTM Pretrain weights loaded
outv: (?, 200, 256)
outa: (?, 200, 256)
attn_out: (?, 200, 256)
attn_states: (?, 200, 200)
fusion: (?, 200, 512)
up1: (?, 700, 256)
up2: (?, 2700, 64)
up3: (?, 10700, 16)
up4: (?, 32025, 4)
out_samples: (?, 32000, 1)
output_concats: (?, 32000, 2)

==================================================================================================
Total params: 40,300,399
Trainable params: 40,245,615
Non-trainable params: 54,784
__________________________________________________________________________________________________

Pred: (24, 32000)
GT: (24, 32000)
Pred: (24, 32000)
GT: (24, 32000)
Pred: (24, 32000)
GT: (24, 32000)
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Epoch 1/2
1/5 [=====>........................] - ETA: 8:38 - loss: 50.1540 - snr_acc: -50.15402/5 [===========>..................] - ETA: 3:16 - loss: 50.4364 - snr_acc: -50.43643/5 [=================>............] - ETA: 1:28 - loss: 48.4299 - snr_acc: -48.42994/5 [=======================>......] - ETA: 33s - loss: 48.2614 - snr_acc: -48.2614  1/10 [==>...........................] - ETA: 1:23 - loss: 47.1593 - snr_acc: -47.1593 2/10 [=====>........................] - ETA: 38s - loss: 45.5753 - snr_acc: -45.5753  3/10 [========>.....................] - ETA: 23s - loss: 45.2284 - snr_acc: -45.2284 4/10 [===========>..................] - ETA: 15s - loss: 46.1194 - snr_acc: -46.1194 5/10 [==============>...............] - ETA: 10s - loss: 46.1739 - snr_acc: -46.1739 6/10 [=================>............] - ETA: 7s - loss: 46.5505 - snr_acc: -46.5505  7/10 [====================>.........] - ETA: 4s - loss: 46.3167 - snr_acc: -46.3167 8/10 [=======================>......] - ETA: 2s - loss: 46.2161 - snr_acc: -46.2161 9/10 [==========================>...] - ETA: 1s - loss: 46.0044 - snr_acc: -46.004410/10 [==============================] - 12s 1s/step - loss: 45.7604 - snr_acc: -45.7604
Traceback (most recent call last):
  File "main_tasnet.py", line 167, in <module>
    callbacks=[reducelronplateau, checkpoint_save_weights, LoggingCallback(print_fcn=log_to_file), metrics_crm], verbose = 1)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training.py", line 1426, in fit_generator
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python3.5/dist-packages/wandb/keras/__init__.py", line 104, in new_generator
    return old_generator(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/training_generator.py", line 232, in model_iteration
    callbacks.on_epoch_end(epoch, epoch_logs, mode=mode)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/callbacks.py", line 251, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/data/AV-speech-separation1/metrics.py", line 339, in on_epoch_end
    val_folders_samp = [self.val_folders[20], self.val_folders[30],self.val_folders[40],self.val_folders[50],self.val_folders[60],self.val_folders[80],self.val_folders[12],self.val_folders[1400],self.val_folders[-1], self.val_folders[-305],self.val_folders[-4],self.val_folders[-5],self.val_folders[-6],self.val_folders[-8],self.val_folders[-12],self.val_folders[-10]]
IndexError: list index out of range
